module.exports = [
  { category: "general", difficulty: "easy", q: "What colour is the sky on a clear day?", choices: ["Blue", "Green", "Purple", "Orange"], answer: 0 },
  { category: "general", difficulty: "easy", q: "How many days are in a leap year?", choices: ["365", "366", "364", "360"], answer: 1 },
  { category: "general", difficulty: "easy", q: "What is 7 × 8?", choices: ["54", "56", "63", "48"], answer: 1 },
  { category: "science", difficulty: "easy", q: "What planet is known as the Red Planet?", choices: ["Venus", "Mars", "Jupiter", "Mercury"], answer: 1 },
  { category: "science", difficulty: "medium", q: "What gas do plants absorb from the air?", choices: ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"], answer: 2 },
  { category: "science", difficulty: "medium", q: "What is H2O more commonly known as?", choices: ["Salt", "Water", "Hydrogen", "Acid"], answer: 1 },
  { category: "science", difficulty: "hard", q: "What particle has a negative charge?", choices: ["Proton", "Neutron", "Electron", "Photon"], answer: 2 },
  { category: "gaming", difficulty: "easy", q: "In Minecraft, what do you need to craft a torch?", choices: ["Stick + coal", "Iron + wood", "Sand + glass", "Dirt + seed"], answer: 0 },
  { category: "gaming", difficulty: "medium", q: "What company developed Fortnite?", choices: ["Valve", "Epic Games", "Ubisoft", "EA"], answer: 1 },
  { category: "gaming", difficulty: "hard", q: "What year was the original PlayStation released in Japan?", choices: ["1992", "1994", "1996", "1998"], answer: 1 },
  { category: "geography", difficulty: "easy", q: "What is the capital of France?", choices: ["Lyon", "Marseille", "Paris", "Nice"], answer: 2 },
  { category: "geography", difficulty: "medium", q: "Which ocean is the largest?", choices: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: 3 },
  { category: "geography", difficulty: "hard", q: "What is the capital of Kazakhstan?", choices: ["Almaty", "Astana", "Tashkent", "Bishkek"], answer: 1 },
  { category: "history", difficulty: "easy", q: "Who was the first President of the United States?", choices: ["Lincoln", "Washington", "Jefferson", "Adams"], answer: 1 },
  { category: "history", difficulty: "medium", q: "In which year did World War II end?", choices: ["1943", "1944", "1945", "1946"], answer: 2 },
  { category: "history", difficulty: "hard", q: "The Magna Carta was signed in which century?", choices: ["11th", "12th", "13th", "14th"], answer: 2 },
  { category: "tech", difficulty: "easy", q: "What does CPU stand for?", choices: ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Power Unit"], answer: 0 },
  { category: "tech", difficulty: "medium", q: "Which language is primarily used for web page structure?", choices: ["CSS", "HTML", "Python", "SQL"], answer: 1 },
  { category: "tech", difficulty: "hard", q: "What does HTTP stand for?", choices: ["HyperText Transfer Protocol", "High Transfer Text Process", "Hyperlink Text Transmission Protocol", "Host Transfer Type Protocol"], answer: 0 },
  { category: "fun", difficulty: "easy", q: "How many sides does a hexagon have?", choices: ["5", "6", "7", "8"], answer: 1 },
  { category: "fun", difficulty: "medium", q: "What is the chemical symbol for gold?", choices: ["Ag", "Au", "Gd", "Go"], answer: 1 },
  { category: "fun", difficulty: "hard", q: "What is the square root of 144?", choices: ["11", "12", "13", "14"], answer: 1 }
];
